name: Build and Release

on:
  push:
    tags:
      - 'v*'

jobs:
  build:
    runs-on: macos-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'
    
    - name: Install dependencies
      run: |
        brew install exempi
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install pyinstaller
    
    - name: Build app
      run: pyinstaller gui.spec
    
    - name: Create ZIP archive
      run: cd dist && zip -r ../MSUK-Description-Fixer.zip MSUK-Description-Fixer.app
    
    - name: Create Github Release
      uses: actions/create-release@v1
      if: startsWith(github.ref, 'refs/tags/')
      env:
        GITHUB_TOKEN: ${{ secrets.ACTION_SECRET }}
      with:
        tag_name: ${{ github.ref }}
        release_name: ${{ github.ref }}
        body: ${{ github.ref }}
        draft: false
        prerelease: false
        files: MSUK-Description-Fixer.zip
